services:
  web:
    build: .
    ports:
      - 8000:4000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_DATABASE: pa11y-webservice
